// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Modals.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_new_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_new_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201504302251462_Add_new_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
